catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import HomepageListView, contacts, Current_prodDetailView, BlogPostDetailView, BlogPostCreateView

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomepageListView.as_view(), name='homepage'),
    path('contacts/', contacts, name='contacts'),
    path('current_prod', Current_prodDetailView.as_view(), name='current_prod'),
    path('blog_post/', BlogPostCreateView.as_view(), name='blog_post')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models/models.py
from django.utils.text import slugify

from django.db import models


NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):

    category_name = models.CharField(max_length=150, verbose_name='Название категории')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f"{self.category_name}"

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('pk',)


class Product(models.Model):
    product_name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='images/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name='Цена за покупку')
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    last_change_date = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')

    def __str__(self):
        return f"Наименование: {self.product_name}. " \
               f"Категория: {self.category}. " \
               f"Цена за покупку: {self.price}. " \
               f"Дата создания: {self.date_created}"

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('pk',)


class BlogPost(models.Model):
    title = models.CharField(max_length=200, verbose_name='название')
    slug = models.CharField(max_length=200, unique=True, verbose_name='URL')
    content = models.TextField(verbose_name='Описание')
    preview = models.ImageField(upload_to='images/', verbose_name='Изображение', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=False)
    views_count = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'

catalog/models/posts.py
# from django.db import models
#
# NULLABLE = {'blank':True, 'null': True}
#
#
# class Owner(models.Model):
#     pass
#
#
# class Comment(models.Model):
#     title = models.CharField(max_length=50, verbose_name='название')
#     slug = models.CharField(max_length=200, unique=True, verbose_name='URL')
#     description = models.TextField(verbose_name='Описание')
#     image = models.ImageField(upload_to='images/', verbose_name='Изображение', **NULLABLE)
#     create_date = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
#     is_published = models.BooleanField(default=False)
#     views_count = models.IntegerField(default=0)
#
#     def __str__(self):
#         return f"{self.title}"
#
#     def Meta:
#         verbose_name = 'комментарий'
#         verbose_name_plural = 'комментарии'

catalog/views.py
from django.shortcuts import render

from catalog.models.models import Product, BlogPost
from django.views import generic
from django.urls import reverse_lazy


class HomepageListView(generic.ListView):
    model = Product
    extra_context = {
        'title': 'Магазин'
    }


class Current_prodDetailView(generic.DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = context_data['object']
        return context_data


# def current_prod(request):
#     products_list = Product.objects.all()
#     context = {
#         'object_list': products_list
#     }
#     return render(request, 'catalog/homepage.html', context)


# class ContactsListView(generic.ListView):
#     model = Product
#      extra_context = {
#          'title': 'Контакты'
#      }

def contacts(request):
    extra_context = {
        'title': 'Контакты'
    }
    return render(request, 'catalog/contact.html')


class BlogPostListView(generic.ListView):
    model = BlogPost
    template_name = 'blogpost_list.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return BlogPost.objects.filter(is_published=True)


class BlogPostDetailView(generic.DetailView):
    model = BlogPost
    template_name = 'blogpost_detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.views_count += 1
        self.object.save()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class BlogPostCreateView(generic.CreateView):
    model = BlogPost
    template_name = 'catalog/blogpost_form.html'
    fields = ['title', 'content', 'preview', 'is_published']


class BlogPostUpdateView(generic.UpdateView):
    model = BlogPost
    template_name = 'catalog/blogpost_form.html'
    fields = ['title', 'content', 'preview', 'is_published']

    def get_success_url(self):
        return reverse_lazy('blogpost_detail', kwargs={'slug': self.object.slug})


class BlogPostDeleteView(generic.DeleteView):
    model = BlogPost
    template_name = 'blogpost_confirm_delete.html'
    success_url = reverse_lazy('blogpost_list')

catalog/templates/catalog/blogpost_form.html
html
{% for post in posts %}
  <div class="post">
    <h2><a href="{% url 'blogpost_detail' slug=post.slug %}">{{ post.title }}</a></h2>
    <p>{{ post.content }}</p>
    <img src="{{ post.preview.url }}" alt="{{ post.title }}">
    <p>Views: {{ post.views_count }}</p>
  </div>
{% endfor %}

catalog/templates/catalog/contact.html
{% extends 'catalog/contacts_list.html' %}
{% block content %}
    <div class="card-header">
        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
    </div>
    <div class="card-body">
        <form method="post" action="" class="form-floating">
            {% csrf_token %}
            <div class="mb-3">
                <label for="name">Имя</label>
                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
            </div>
            <div class="mb-3">
                <label for="phone">Телефон</label>
                <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон"
                       required>
            </div>
            <div class="mb-3">
                <label for="message">Сообщение</label>
                <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон"
                          required></textarea>
            </div>
        </form>
        <a href="#" type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</a>
    </div>
{% endblock %}

catalog/templates/catalog/contacts_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

{% include 'catalog/includes/inc_homepage.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Омск,Россия</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>

            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/homepage.html
{% load static %}
{% load my_tags %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>

{% include 'catalog/includes/inc_homepage.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
    <p class="lead">Онлайн Магазин - это отличный вариант, если вы хотите что нибудь купить!</p>
</div>

<div class="container">
    <div class="row text-center">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                {{ title }}
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>

            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/includes/inc_homepage.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Магазин</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:homepage' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
    </nav>
</div>

catalog/templates/catalog/product_list.html
{% extends 'catalog/homepage.html' %}
{% load my_tags %}
{% block content %}
    {% for object in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <img src="{{ object.image|media_path }}" class="img-fluid" alt="IMAGE" width="350px"
                             height="350px">
                    </div>
                    <div class="card-body">
                        <p>{{ object.product_name }}</p>
                        <p>{{ object.category }}</p>
                        <p>{{ object.description|truncatechars:100 }}</p>
                        <p>{{ object.price }}</p>
                        <p>{{ object.date_created|date:'d-m-Y' }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
{% endblock %}